title: Romancing the Stones
description: >-
  Proxy Vintage series in Austin, TX. Heavy on beer.
baseurl: ""
url: "https://stonesmtg.com"
timezone: America/Chicago
future: true

# Fix this when they fix the channel url
#youtube_username: Romancing the Stones
twitter_username: StonesVintage
facebook_username: RomancingTheStones
#email: rts@stonesmtg.com

permalink: /:title

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

exclude:
  - .gitignore
  - .bundle
  - Gemfile
  - Gemfile.lock
  - vendor

# I've been overcomplicating this.
# Just put an announcement in _announcements
# Then put the results in _results
# Pros:
# * super simple
# * things are where they need to be
# Con:
# * The results need to link to the announcement, which we can do
#   automatically with a template.
# * If we fail to create a results page, the event just disappears
#   because we don't display announcements in the past.  We could
#   just always make a symlink in results to the announcement, and
#   then replace that with a real file when the time comes.
collections:
  results:
    permalink: /results/:year-:month-:day
    output: true
  announcements:
    permalink: /announce/:year-:month-:day
    output: true
  articles:
    permalink: /article/:title
    output: true
  header_pages:
    output: true
